/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Sistema.Colores;
import Modelo.Sistema.MetodosVentana;
import Modelo.Sistema.Sistema;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Idea
 */
public class AdmProgresos extends javax.swing.JDialog {

    /**
     * Creates new form NuevoUsuario
     */
    private final MatteBorder borde = new MatteBorder(1,1,1,1,Colores.MenuShadow);
    private CardLayout cardlayout;
    
    public AdmProgresos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground( Colores.WorkspaceBackground );
        this.getRootPane().setBorder(borde);
        cardlayout = (CardLayout)this.cards.getLayout();
        limpiarNuevoEditar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new Modelo.Controles.MenuBar(this);
        cards = new javax.swing.JPanel();
        admin = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        labelTitle4 = new Modelo.Controles.LabelTitle();
        jScrollPane1 = new javax.swing.JScrollPane();
        list1 = new Modelo.Controles.List();
        labelIdentifier14 = new Modelo.Controles.LabelIdentifier();
        btEditar = new Modelo.Controles.ButtonNormalV();
        btEliminar = new Modelo.Controles.ButtonNormalR();
        btNuevo = new Modelo.Controles.ButtonNormalV();
        btSalir = new Modelo.Controles.ButtonNormalR();
        nuevoEditar = new javax.swing.JPanel();
        labelTitle3 = new Modelo.Controles.LabelTitle();
        labelIdentifier15 = new Modelo.Controles.LabelIdentifier();
        tfPeso = new Modelo.Controles.TextField();
        labelIdentifier16 = new Modelo.Controles.LabelIdentifier();
        tfHombros = new Modelo.Controles.TextField();
        labelIdentifier17 = new Modelo.Controles.LabelIdentifier();
        tfPecho = new Modelo.Controles.TextField();
        labelIdentifier18 = new Modelo.Controles.LabelIdentifier();
        tfCintura = new Modelo.Controles.TextField();
        labelIdentifier19 = new Modelo.Controles.LabelIdentifier();
        tfGluteos = new Modelo.Controles.TextField();
        labelIdentifier20 = new Modelo.Controles.LabelIdentifier();
        labelIdentifier21 = new Modelo.Controles.LabelIdentifier();
        tfBisIzqRe = new Modelo.Controles.TextField();
        labelIdentifier22 = new Modelo.Controles.LabelIdentifier();
        tfBisDerRe = new Modelo.Controles.TextField();
        labelIdentifier23 = new Modelo.Controles.LabelIdentifier();
        tfPiernaIzq = new Modelo.Controles.TextField();
        labelIdentifier24 = new Modelo.Controles.LabelIdentifier();
        tfPantorrillaIzq = new Modelo.Controles.TextField();
        labelIdentifier26 = new Modelo.Controles.LabelIdentifier();
        tfBisIzqTen = new Modelo.Controles.TextField();
        labelIdentifier27 = new Modelo.Controles.LabelIdentifier();
        tfBisDerTen = new Modelo.Controles.TextField();
        labelIdentifier28 = new Modelo.Controles.LabelIdentifier();
        tfPiernaDer = new Modelo.Controles.TextField();
        labelIdentifier29 = new Modelo.Controles.LabelIdentifier();
        tfPantorrillaDer = new Modelo.Controles.TextField();
        btAceptar = new Modelo.Controles.ButtonNormalV();
        btCancelar = new Modelo.Controles.ButtonNormalR();
        tfFecha = new Modelo.Controles.dateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout menuBar1Layout = new javax.swing.GroupLayout(menuBar1);
        menuBar1.setLayout(menuBar1Layout);
        menuBar1Layout.setHorizontalGroup(
            menuBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        menuBar1Layout.setVerticalGroup(
            menuBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        cards.setBackground(new java.awt.Color(250, 250, 250));
        cards.setLayout(new java.awt.CardLayout());

        admin.setBackground(new java.awt.Color(250, 250, 250));

        jPanel3.setBackground(new java.awt.Color(190, 219, 228));

        labelTitle4.setText("REGISTROS DE PROGRESOS");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(300, 300, 300))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(labelTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        list1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "22/Octubre/2013", "22/Noviembre/2013", "22/Diciembreo/2013", "22/Enero/2014", "22/Febrero/2014", "22/Marzo/2014" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list1);

        labelIdentifier14.setText("actualmente registrados");

        btEditar.setText("d");
        btEditar.setToolTipText("Editar seleccionado");

        btEliminar.setText("b");
        btEliminar.setToolTipText("Eliminar seleccionado");

        btNuevo.setText("c");
        btNuevo.setToolTipText("Nuevo registro de progresos");
        btNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNuevoActionPerformed(evt);
            }
        });

        btSalir.setText("n");
        btSalir.setToolTipText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout adminLayout = new javax.swing.GroupLayout(admin);
        admin.setLayout(adminLayout);
        adminLayout.setHorizontalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(adminLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(adminLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(adminLayout.createSequentialGroup()
                        .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(adminLayout.createSequentialGroup()
                                .addComponent(btNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(adminLayout.createSequentialGroup()
                                .addComponent(labelIdentifier14, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(174, 174, 174)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 287, Short.MAX_VALUE)
                        .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))))
        );
        adminLayout.setVerticalGroup(
            adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelIdentifier14, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(adminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46))
        );

        cards.add(admin, "card3");

        nuevoEditar.setBackground(new java.awt.Color(250, 250, 250));

        labelTitle3.setText("NUEVO REGISTRO DE PROGRESOS");

        labelIdentifier15.setText("peso");

        labelIdentifier16.setText("hombros");

        labelIdentifier17.setText("pecho");

        labelIdentifier18.setText("cintura");

        labelIdentifier19.setText("gluteos");

        labelIdentifier20.setText("fecha");

        labelIdentifier21.setText("bisep izquierdo relajado");

        labelIdentifier22.setText("bisep derecho relajado");

        labelIdentifier23.setText("pierna izquierda");

        labelIdentifier24.setText("pantorrilla izquierda");

        labelIdentifier26.setText("bisep izquierdo tensionado");

        labelIdentifier27.setText("bisep derecho tensionado");

        labelIdentifier28.setText("pierna derecha");

        labelIdentifier29.setText("pantorrilla derecha");

        btAceptar.setText("5");
        btAceptar.setToolTipText("Aceptar");
        btAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptarActionPerformed(evt);
            }
        });

        btCancelar.setText("6");
        btCancelar.setToolTipText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout nuevoEditarLayout = new javax.swing.GroupLayout(nuevoEditar);
        nuevoEditar.setLayout(nuevoEditarLayout);
        nuevoEditarLayout.setHorizontalGroup(
            nuevoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoEditarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(nuevoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(nuevoEditarLayout.createSequentialGroup()
                        .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nuevoEditarLayout.createSequentialGroup()
                        .addGroup(nuevoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(nuevoEditarLayout.createSequentialGroup()
                                .addGroup(nuevoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfGluteos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIdentifier19, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIdentifier18, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIdentifier17, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfHombros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIdentifier16, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIdentifier15, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(nuevoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfPantorrillaIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelIdentifier24, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfPiernaIzq, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelIdentifier23, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfBisDerRe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelIdentifier22, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfBisIzqRe, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(labelIdentifier21, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelIdentifier20, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfFecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(nuevoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdentifier29, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPiernaDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdentifier28, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBisDerTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdentifier27, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfBisIzqTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelIdentifier26, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPantorrillaDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        nuevoEditarLayout.setVerticalGroup(
            nuevoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nuevoEditarLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(labelTitle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(nuevoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(nuevoEditarLayout.createSequentialGroup()
                        .addComponent(labelIdentifier26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBisIzqTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelIdentifier27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfBisDerTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelIdentifier28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPiernaDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelIdentifier29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfPantorrillaDer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nuevoEditarLayout.createSequentialGroup()
                        .addGroup(nuevoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(nuevoEditarLayout.createSequentialGroup()
                                .addComponent(labelIdentifier20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(nuevoEditarLayout.createSequentialGroup()
                                .addComponent(labelIdentifier15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(nuevoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoEditarLayout.createSequentialGroup()
                                .addComponent(labelIdentifier16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfHombros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelIdentifier17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPecho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelIdentifier18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfCintura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelIdentifier19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfGluteos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nuevoEditarLayout.createSequentialGroup()
                                .addComponent(labelIdentifier21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfBisIzqRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelIdentifier22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfBisDerRe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelIdentifier23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPiernaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelIdentifier24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfPantorrillaIzq, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(nuevoEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        cards.add(nuevoEditar, "card2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 780, Short.MAX_VALUE)
            .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(cards, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        MetodosVentana.CerrarVentana(this);
    }//GEN-LAST:event_btSalirActionPerformed

    private void btNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNuevoActionPerformed
        IrANuevoEditar();
    }//GEN-LAST:event_btNuevoActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        cardlayout.show(cards, "card3");
        limpiarNuevoEditar();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void btAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptarActionPerformed
        Validar();              
    }//GEN-LAST:event_btAceptarActionPerformed
    
    private void IrANuevoEditar(){
        cardlayout.show(cards, "card2");
    }
    
    private void limpiarNuevoEditar(){
        this.tfPeso.setPlaceholder("¿Cual es el peso?");
        this.tfHombros.setPlaceholder("¿Cuanto miden los hombros?");
        this.tfPecho.setPlaceholder("¿Cuanto mide el pecho?");
        this.tfCintura.setPlaceholder("¿Cuanto mide la cintura?");
        this.tfGluteos.setPlaceholder("¿Cuanto miden los gluteos?");
        
        this.tfBisIzqRe.setPlaceholder("¿Cuanto mide el bisep izquierdo relajado?");
        this.tfBisIzqTen.setPlaceholder("¿Cuanto mide el bisep izquierdo tensionado?");
        this.tfBisDerRe.setPlaceholder("¿Cuanto mide el bisep derecho relajado?");
        this.tfBisDerTen.setPlaceholder("Cuanto mide el bisep derecho tensionado");
        
        this.tfPiernaIzq.setPlaceholder("¿Cuanto mide la pierna izquierda?");
        this.tfPiernaDer.setPlaceholder("¿Cuanto mide la pierna derecha?");
        this.tfPantorrillaIzq.setPlaceholder("¿Cuanto mide la pantorrilla izquierda?");
        this.tfPantorrillaDer.setPlaceholder("¿Cuanto mide la pantorrilla derecha?");
    }
    
    private boolean Validar(){
        boolean ok = true;
        if(this.tfPeso.getText().equals(this.tfPeso.getPlaceholder())){
            this.tfPeso.setErrorStatus(true);
            ok = false;
        }
        if(this.tfHombros.getText().equals(this.tfHombros.getPlaceholder())){
            this.tfHombros.setErrorStatus(true);
            ok = false;
        }
        if(this.tfPecho.getText().equals(this.tfPecho.getPlaceholder())){
            this.tfPecho.setErrorStatus(true);
            ok = false;
        }
        if(this.tfCintura.getText().equals(this.tfCintura.getPlaceholder())){
            this.tfCintura.setErrorStatus(true);
            ok = false;
        }
        if(this.tfGluteos.getText().equals(this.tfGluteos.getPlaceholder())){
            this.tfGluteos.setErrorStatus(true);
            ok = false;
        }
        
        if(this.tfBisIzqRe.getText().equals(this.tfBisIzqRe.getPlaceholder())){
            this.tfBisIzqRe.setErrorStatus(true);
            ok = false;
        }
        if(this.tfBisIzqTen.getText().equals(this.tfBisIzqTen.getPlaceholder())){
            this.tfBisIzqTen.setErrorStatus(true);
            ok = false;
        }
        if(this.tfBisDerRe.getText().equals(this.tfBisDerRe.getPlaceholder())){
            this.tfBisDerRe.setErrorStatus(true);
            ok = false;
        }
        if(this.tfBisDerTen.getText().equals(this.tfBisDerTen.getPlaceholder())){
            this.tfBisDerTen.setErrorStatus(true);
            ok = false;
        }
        if(this.tfPiernaIzq.getText().equals(this.tfPiernaIzq.getPlaceholder())){
            this.tfPiernaIzq.setErrorStatus(true);
            ok = false;
        }
        if(this.tfPiernaDer.getText().equals(this.tfPiernaDer.getPlaceholder())){
            this.tfPiernaDer.setErrorStatus(true);
            ok = false;
        }
        if(this.tfPantorrillaIzq.getText().equals(this.tfPantorrillaIzq.getPlaceholder())){
            this.tfPantorrillaIzq.setErrorStatus(true);
            ok = false;
        }
        if(this.tfPantorrillaDer.getText().equals(this.tfPantorrillaDer.getPlaceholder())){
            this.tfPantorrillaDer.setErrorStatus(true);
            ok = false;
        }
//        String n = new String(pfContraseña.getPassword());
//        JOptionPane.showMessageDialog(this,n);
        return ok;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel admin;
    private Modelo.Controles.ButtonNormalV btAceptar;
    private Modelo.Controles.ButtonNormalR btCancelar;
    private Modelo.Controles.ButtonNormalV btEditar;
    private Modelo.Controles.ButtonNormalR btEliminar;
    private Modelo.Controles.ButtonNormalV btNuevo;
    private Modelo.Controles.ButtonNormalR btSalir;
    private javax.swing.JPanel cards;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private Modelo.Controles.LabelIdentifier labelIdentifier14;
    private Modelo.Controles.LabelIdentifier labelIdentifier15;
    private Modelo.Controles.LabelIdentifier labelIdentifier16;
    private Modelo.Controles.LabelIdentifier labelIdentifier17;
    private Modelo.Controles.LabelIdentifier labelIdentifier18;
    private Modelo.Controles.LabelIdentifier labelIdentifier19;
    private Modelo.Controles.LabelIdentifier labelIdentifier20;
    private Modelo.Controles.LabelIdentifier labelIdentifier21;
    private Modelo.Controles.LabelIdentifier labelIdentifier22;
    private Modelo.Controles.LabelIdentifier labelIdentifier23;
    private Modelo.Controles.LabelIdentifier labelIdentifier24;
    private Modelo.Controles.LabelIdentifier labelIdentifier26;
    private Modelo.Controles.LabelIdentifier labelIdentifier27;
    private Modelo.Controles.LabelIdentifier labelIdentifier28;
    private Modelo.Controles.LabelIdentifier labelIdentifier29;
    private Modelo.Controles.LabelTitle labelTitle3;
    private Modelo.Controles.LabelTitle labelTitle4;
    private Modelo.Controles.List list1;
    private Modelo.Controles.MenuBar menuBar1;
    private javax.swing.JPanel nuevoEditar;
    private Modelo.Controles.TextField tfBisDerRe;
    private Modelo.Controles.TextField tfBisDerTen;
    private Modelo.Controles.TextField tfBisIzqRe;
    private Modelo.Controles.TextField tfBisIzqTen;
    private Modelo.Controles.TextField tfCintura;
    private Modelo.Controles.dateChooser tfFecha;
    private Modelo.Controles.TextField tfGluteos;
    private Modelo.Controles.TextField tfHombros;
    private Modelo.Controles.TextField tfPantorrillaDer;
    private Modelo.Controles.TextField tfPantorrillaIzq;
    private Modelo.Controles.TextField tfPecho;
    private Modelo.Controles.TextField tfPeso;
    private Modelo.Controles.TextField tfPiernaDer;
    private Modelo.Controles.TextField tfPiernaIzq;
    // End of variables declaration//GEN-END:variables
}
