/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Modelo.Sistema.Colores;
import Modelo.Sistema.MetodosVentana;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import javax.swing.JOptionPane;
import javax.swing.border.MatteBorder;

/**
 *
 * @author Idea
 */
public class ProgresosCliente extends javax.swing.JDialog {

    /**
     * Creates new form NuevoUsuario
     */
 
    private final MatteBorder borde = new MatteBorder(1,1,1,1,Colores.MenuShadow);
    private final Graphics go;
    
    public ProgresosCliente(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground( Colores.WorkspaceBackground );
        this.getRootPane().setBorder(borde);
        go = graphicMuscSys1.getGraphics();
       //inicializar();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new Modelo.Controles.MenuBar(this);
        clientes = new javax.swing.JPanel();
        lidentifier = new Modelo.Controles.LabelIdentifier();
        btCalcular = new Modelo.Controles.ButtonNormalV();
        jPanel3 = new javax.swing.JPanel();
        labelTitle4 = new Modelo.Controles.LabelTitle();
        btSalir = new Modelo.Controles.ButtonNormalR();
        labelSubtitle1 = new Modelo.Controles.LabelSubtitle();
        coord1 = new Modelo.Controles.LabelIdentifier();
        comboBox1 = new Modelo.Controles.comboBox();
        comboBox2 = new Modelo.Controles.comboBox();
        labelTitleBig1 = new Modelo.Controles.LabelTitleBig();
        labelIdentifier1 = new Modelo.Controles.LabelIdentifier();
        labelSubtitle2 = new Modelo.Controles.LabelSubtitle();
        labelSubtitle3 = new Modelo.Controles.LabelSubtitle();
        labelIdentifier2 = new Modelo.Controles.LabelIdentifier();
        labelTitle1 = new Modelo.Controles.LabelTitle();
        btGenerarReporte = new Modelo.Controles.ButtonNormalV();
        coord = new Modelo.Controles.LabelIdentifier();
        graphicMuscSys1 = new Modelo.Controles.GraphicMuscSys();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);

        javax.swing.GroupLayout menuBar1Layout = new javax.swing.GroupLayout(menuBar1);
        menuBar1.setLayout(menuBar1Layout);
        menuBar1Layout.setHorizontalGroup(
            menuBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1026, Short.MAX_VALUE)
        );
        menuBar1Layout.setVerticalGroup(
            menuBar1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 71, Short.MAX_VALUE)
        );

        clientes.setBackground(new java.awt.Color(250, 250, 250));

        lidentifier.setText("fecha inicial");

        btCalcular.setText("m");
        btCalcular.setToolTipText("Calcular progresos");

        jPanel3.setBackground(new java.awt.Color(190, 219, 228));

        labelTitle4.setText("PROGRESOS DE PERENGANO DE TAL");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitle4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(36, Short.MAX_VALUE)
                .addComponent(labelTitle4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        btSalir.setText("6");
        btSalir.setToolTipText("Salir");
        btSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalirActionPerformed(evt);
            }
        });

        labelSubtitle1.setText("Criterios de comparacion");

        coord1.setText("fecha final");

        labelTitleBig1.setText("PIERNA DERECHA");

        labelIdentifier1.setText("20 de Enero del 2014");

        labelSubtitle2.setText("45.48cm");

        labelSubtitle3.setText("46.20cm");

        labelIdentifier2.setText("31 de Marzo del 2014");

        labelTitle1.setText("Aumento de 1.58%");

        btGenerarReporte.setText("f");
        btGenerarReporte.setToolTipText("Generar reporte completo");
        btGenerarReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGenerarReporteActionPerformed(evt);
            }
        });

        coord.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        coord.setText("coordenadas");

        graphicMuscSys1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                graphicMuscSys1MouseMoved(evt);
            }
        });

        javax.swing.GroupLayout graphicMuscSys1Layout = new javax.swing.GroupLayout(graphicMuscSys1);
        graphicMuscSys1.setLayout(graphicMuscSys1Layout);
        graphicMuscSys1Layout.setHorizontalGroup(
            graphicMuscSys1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 313, Short.MAX_VALUE)
        );
        graphicMuscSys1Layout.setVerticalGroup(
            graphicMuscSys1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout clientesLayout = new javax.swing.GroupLayout(clientes);
        clientes.setLayout(clientesLayout);
        clientesLayout.setHorizontalGroup(
            clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(clientesLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientesLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(clientesLayout.createSequentialGroup()
                        .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(clientesLayout.createSequentialGroup()
                                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(comboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lidentifier, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(coord1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(coord, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(graphicMuscSys1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(labelSubtitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 590, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelTitleBig1, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(clientesLayout.createSequentialGroup()
                                    .addGap(22, 22, 22)
                                    .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelIdentifier1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(labelSubtitle2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(labelIdentifier2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelSubtitle3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelTitle1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(30, 30, 30))
        );
        clientesLayout.setVerticalGroup(
            clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(clientesLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(labelSubtitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(clientesLayout.createSequentialGroup()
                        .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(clientesLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lidentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(coord1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(comboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(clientesLayout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(labelTitleBig1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelIdentifier1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(labelSubtitle2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelIdentifier2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(labelSubtitle3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(labelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
                        .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btGenerarReporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, clientesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(clientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(graphicMuscSys1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, clientesLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(coord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(88, 88, 88))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(menuBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 1026, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(menuBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 564, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(0, 67, Short.MAX_VALUE)
                    .addComponent(clientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalirActionPerformed
        MetodosVentana.CerrarVentana(this);
    }//GEN-LAST:event_btSalirActionPerformed

    private void btGenerarReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGenerarReporteActionPerformed
        // TODO add your handling code here:
        this.graphicMuscSys1.setSexo(1);
    }//GEN-LAST:event_btGenerarReporteActionPerformed

    private void graphicMuscSys1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_graphicMuscSys1MouseMoved
        int x = evt.getX();
        int y = evt.getY();

        this.coord.setText("(X:" + x + ")(Y:" + y + ")");
//        
//            Graphics2D g2d = (Graphics2D) go;
//            RenderingHints rh =
//                new RenderingHints(RenderingHints.KEY_ANTIALIASING, 
//                RenderingHints.VALUE_ANTIALIAS_ON);
//
//            rh.put(RenderingHints.KEY_RENDERING,
//                   RenderingHints.VALUE_RENDER_QUALITY);
//
//            g2d.setRenderingHints(rh);
//            g2d.setColor(Colores.NButton);
//            g2d.fillOval(evt.getX(),evt.getY(),10,10);
            
    }//GEN-LAST:event_graphicMuscSys1MouseMoved
    
    private void inicializar(){
        
    }
    /*
    private void inicializar(){
        this.tfNombre.setPlaceholder("¿Cual es el nombre del articulo?");
        this.tfAlmacen.setPlaceholder("¿Cantidad disponible en almacen?");
        this.tfStock.setPlaceholder("¿Cantidad minima en almacen?");
        this.tfDescripcion.setPlaceholder("Describa el articulo");
        this.tfPrecioVenta.setPlaceholder("¿Cual es el precio de venta?");
        this.tfPrecioCompra.setPlaceholder("¿Cual es el precio de compra?");
    }
    
    private boolean Validar(){
        boolean ok = true;
        if(this.tfNombre.getText().equals(this.tfNombre.getPlaceholder())){
            this.tfNombre.setErrorStatus(true);
            ok = false;
        }
        if(this.tfAlmacen.getText().equals(this.tfAlmacen.getPlaceholder())){
            this.tfAlmacen.setErrorStatus(true);
            ok = false;
        }
        if(this.tfAlmacen.getText().equals(this.tfAlmacen.getPlaceholder())){
            this.tfAlmacen.setErrorStatus(true);
            ok = false;
        }
        if(this.tfStock.getText().equals(this.tfStock.getPlaceholder())){
            this.tfStock.setErrorStatus(true);
            ok = false;
        }
        if(this.tfPrecioVenta.getText().equals(this.tfPrecioVenta.getPlaceholder())){
            this.tfPrecioVenta.setErrorStatus(true);
            ok = false;
        }
        if(this.tfPrecioCompra.getText().equals(this.tfPrecioCompra.getPlaceholder())){
            this.tfPrecioCompra.setErrorStatus(true);
            ok = false;
        }
//        String n = new String(pfContraseña.getPassword());
//        JOptionPane.showMessageDialog(this,n);
        return ok;
    }
    */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Modelo.Controles.ButtonNormalV btCalcular;
    private Modelo.Controles.ButtonNormalV btGenerarReporte;
    private Modelo.Controles.ButtonNormalR btSalir;
    private javax.swing.JPanel clientes;
    private Modelo.Controles.comboBox comboBox1;
    private Modelo.Controles.comboBox comboBox2;
    private Modelo.Controles.LabelIdentifier coord;
    private Modelo.Controles.LabelIdentifier coord1;
    private Modelo.Controles.GraphicMuscSys graphicMuscSys1;
    private javax.swing.JPanel jPanel3;
    private Modelo.Controles.LabelIdentifier labelIdentifier1;
    private Modelo.Controles.LabelIdentifier labelIdentifier2;
    private Modelo.Controles.LabelSubtitle labelSubtitle1;
    private Modelo.Controles.LabelSubtitle labelSubtitle2;
    private Modelo.Controles.LabelSubtitle labelSubtitle3;
    private Modelo.Controles.LabelTitle labelTitle1;
    private Modelo.Controles.LabelTitle labelTitle4;
    private Modelo.Controles.LabelTitleBig labelTitleBig1;
    private Modelo.Controles.LabelIdentifier lidentifier;
    private Modelo.Controles.MenuBar menuBar1;
    // End of variables declaration//GEN-END:variables
}
